### ISSUE TITLE
Version 0.7 not available on grails plugins repository

### ISSUE THREAD

**Issue by zeludo** [pedjak/grails-marshallers#26]
Hi,

The latest available version is 0.6 : https://repo.grails.org/grails/plugins/org/grails/plugins/marshallers/
Could you please deploy the 0.7 ?

Thanks

**Comment by dhalupa** [comment]
The 0.7 release of the plugin has been submitted to the approval process. Try leaving a comment, it might speed things up
https://grails.org/plugins/pending/1451
